# Generated by Django 6.0.3 on 2026-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BBA', 'Business Management'), ('cs', 'Computer Science'), ('it', 'Information Technology'), ('entc', 'Electronics & Telecom'), ('mech', 'Mechanical'), ('civil', 'Civil'), ('electrical', 'Electrical'), ('other', 'Other')], max_length=20),
        ),
    ]
