# Generated by Django 6.0.3 on 2026-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='experiences',
            field=models.TextField(blank=True, default=''),
        ),
    ]
